name: dokter
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  assorted_layout_widgets: ^7.0.0
  change_app_package_name: ^1.1.0
  bloc: ^8.1.0
  country_icons: ^2.0.2
  equatable: ^2.0.5
  firebase_core: ^1.17.0
  firebase_messaging: ^11.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_multi_formatter: ^2.7.4
  flutter_rating_bar: ^4.0.1
  formz: ^0.4.1
  freezed_annotation: ^2.1.0
  google_fonts: ^3.0.1
  hydrated_bloc: ^8.1.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  pin_code_fields: ^7.4.0
  provider: ^6.0.3
  qr_flutter: ^4.0.0
  timelines: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/icons/home/
    - assets/images/
    - assets/logo/

flutter_gen:
  output: lib/src/core/assets
