// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTICuh83q4XZKiD6q6ensAqzwoWOuMmlg',
    appId: '1:722376118960:web:2fac789343aea56c126175',
    messagingSenderId: '722376118960',
    projectId: 'rs-sehat',
    authDomain: 'rs-sehat.firebaseapp.com',
    storageBucket: 'rs-sehat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADumN3pkr4lnbUwTBRLkHG6BY6N0ZfRFw',
    appId: '1:722376118960:android:74ec13c40e19ebbb126175',
    messagingSenderId: '722376118960',
    projectId: 'rs-sehat',
    storageBucket: 'rs-sehat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS-XxLOF3a_IHUFpD77zWFz7WCDW76J8U',
    appId: '1:722376118960:ios:b625133806548e43126175',
    messagingSenderId: '722376118960',
    projectId: 'rs-sehat',
    storageBucket: 'rs-sehat.appspot.com',
    iosClientId: '722376118960-7pnsape4d384dpviabi94n89atg23ml3.apps.googleusercontent.com',
    iosBundleId: 'com.blitarsehat.dokter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS-XxLOF3a_IHUFpD77zWFz7WCDW76J8U',
    appId: '1:722376118960:ios:b625133806548e43126175',
    messagingSenderId: '722376118960',
    projectId: 'rs-sehat',
    storageBucket: 'rs-sehat.appspot.com',
    iosClientId: '722376118960-7pnsape4d384dpviabi94n89atg23ml3.apps.googleusercontent.com',
    iosBundleId: 'com.blitarsehat.dokter',
  );
}
